CREATE USER SYNCHRO_TASK IDENTIFIED BY SYNCHRO_TASK
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT TO SYNCHRO_TASK;
GRANT CREATE ANY TABLE TO SYNCHRO_TASK;
GRANT CREATE ANY INDEX TO SYNCHRO_TASK;
GRANT SELECT_CATALOG_ROLE TO SYNCHRO_TASK;