@startuml

Instance1 -> LockProvider ++ #FFBBBB : lock [foo, bar]
activate Instance1
LockProvider --> Instance1 : OK
Instance1 -> Instance1 ++: run <<SynchroTask[foo, bar]>>

Instance2 ->x LockProvider: lock [foo, bar]
activate Instance2
LockProvider --> Instance2 : FAILED
deactivate Instance2

Instance1 -> LockProvider -- : unlock [foo, bar]
LockProvider --> Instance1 -- : OK
deactivate Instance1

'LockProvider --> Instance2 : OK
'activate LockProvider #FFBBBB
'Instance2 -> Instance2: run <<SynchroTask[foo, bar]>>
'activate Instance2
'Instance2 -> LockProvider -- : unlock [foo, bar]
'LockProvider --> Instance2 -- : OK
'deactivate Instance2

@enduml