@startuml

Instance1 -> LockProvider ++ #FFBBBB : lock [foo, bar]
activate Instance1
LockProvider --> Instance1 : OK
Instance1 -> Instance1 ++: run <<SynchroTask[foo, bar]>>

Instance2 ->x LockProvider: lock [foo, bar]
activate Instance2
LockProvider --> Instance2 : FAILED
Instance2 -> Instance2 ++ : return NULL
deactivate Instance2
deactivate Instance2

Instance1 -> LockProvider -- : unlock [foo, bar]
LockProvider --> Instance1 -- : OK
deactivate Instance1

@enduml